name: 'Github Action javascript-obfuscator'
author: Kevin Rohn
description: 'Obfuscate javascript by using the javascript-obfuscator'
inputs:

  input_path: 
    description: 'Single file or directory'
    required: true

  output_path: 
    description: 'Output path for single file or directory'
    required: true
  
  compact:
    description: > 
      Disable one line output code compacting.

      Type: boolean
      Default: true
    required: false
  
  control_flow_flattening:
    description: > 
      Enables control flow flattening.
      
      Type: boolean
      Default: false
    required: false

  control_flow_flattening_threshold:
    description: >
      The probability that the control flow flattening transformation will be applied to the node

      Type: boolean
      Default: false
    required: false

  dead_code_injection:
    required: false
    description: >
      Enables dead code injection

      Type: boolean
      Default: false
  dead_code_injection_threshold:
    required: false
    description: >
      The probability that the dead code injection transformation will be applied to the node
      
      Type: boolean
      Default: false
  debug_protection:
    required: false
    description: > 
      Disable browser Debug panel (can cause DevTools enabled browser freeze)

      Type: boolean
      Default: false

  debug_protection_interval:
    required: false
    description: > 
      Sets interval in milliseconds for debug protection so it is working even after page was loaded (can cause DevTools enabled browser freeze)
      
      Type: number
      Default: 0
  disable_console_output:
    required: false
    description: > 
      Allow console.log, console.info, console.error and console.warn messages output into browser console
      
      Type: boolean
      Default: false

  domain_lock:
    required: false
    description: >
      Allows to run the obfuscated source code only on specific domains and/or sub-domains (comma separated)

      Type: string[] (comma separated, without whitespaces)
      Default: []
  domain_lock_redirect_url:
    required: false
    description: > 
      Allows the browser to be redirected to a passed URL if the source code is not run on the domains specified by --domain-lock

      Type: string
      Default: about:blank

  exclude:
    required: false
    description: > 
      A filename or glob which indicates files to exclude from obfuscation

      Type: string[] (comma separated, without whitespaces)
      Default: []

  force_transform_strings:
    required: false
    description: > 
      (comma separated, without whitespaces) Enables force transformation of string literals, which being matched by passed RegExp patterns (comma separated)
      
      Type: string[] (comma separated, without whitespaces)
      Default: []

  identifier_names_cache_path:
    required: false
    description: > 
      Sets path for identifier names cache
      
      Type: Object | null
      Default: null

  identifier_names_generator:
    required: false
    description: > 
      Sets identifier names generator. Values: dictionary, hexadecimal, mangled, mangled-shuffled.

      Type: string
      Default: hexadecimal
  identifiers_dictionary:
    required: false
    description: > 
      Sets prefix for all global identifiers

      Type: string[] (comma separated, without whitespaces)
      Default: []
  identifiers_prefix:
    required: false
    description: > 
      Identifiers dictionary (comma separated) for `--identifier-names-generator dictionary` option

      Type: string
      Default: ''

  ignore_imports:
    required: false
    description: >
      prevents obfuscation of `require` and `dynamic` imports'
      
      Type: boolean
      Default: false

  log:
    required: false
    description: > 
      Enables logging of the information to the console

      Type: boolean
      Default: false

  numbers_to_expressions:
    required: false
    description: > 
      Enables numbers conversion to expressions
      
      Type: boolean
      Default: false

  options_preset:
    required: false
    description: > 
      Allows to set options preset. Values: default, low-obfuscation, medium-obfuscation, high-obfuscation. Default: default

      Type: string
      Default: default

  rename_globals:
    required: false
    description: > 
      Allows to enable obfuscation of global variable and function names with declaration
      
      Type: boolean
      Default: false

  rename_properties:
    required: false
    description: > 
      UNSAFE: Enables renaming of property names. This probably MAY break your code

      Type: boolean
      Default: false

  rename_properties_mode:
    required: false
    description: > 
      Specify `--rename-properties` option mode. Values: safe, unsafe. Default: safe

      Type: string
      Default: safe

  reserved_names:
    required: false
    description: > 
      Disables obfuscation and generation of identifiers, which being matched by passed RegExp patterns (comma separated)

      Type: string[] (comma separated, without whitespaces)
      Default: []

  reserved_strings:
    required: false
    description: > 
      Disables transformation of string literals, which being matched by passed RegExp patterns (comma separated)

      Type: string[] (comma separated, without whitespaces)
      Default: []
  seed:
    required: false
    description: > 
      Sets seed for random generator. This is useful for creating repeatable results.
      
      Type: string|number
      Default: false
      
  self_defending:
    required: false
    description: '<boolean> Disables self-defending for obfuscated code'
  simplify:
    required: false
    description: '<boolean> Enables additional code obfuscation through simplification'
  source_map:
    required: false
    description: '<boolean> Enables source map generation'
  source_map_base_url:
    required: false
    description: '<string> Sets base url to the source map import url when `--source-map-mode=separate`'
  source_map_file_name:
    required: false
    description: 'S<string> ets file name for output source map when `--source-map-mode=separate`'
  source_map_mode:
    required: false
    description: '<string> Specify source map output mode. Values: inline, separate. Default: separate'
  source_map_sources_mode:
    required: false
    description: '<string> Specify source map sources mode. Values: sources, sources-content. Default: sources-content'
  split_strings: 
    required: false
    description: '<boolean> Splits literal strings into chunks with length of `splitStringsChunkLength` option value'
  split_strings_chunk_length:
    required: false
    description: '<number> Sets chunk length of `splitStrings` option'
  string_array:
    required: false
    description: '<boolean> Enables gathering of all literal strings into an array and replacing every literal string with an array call'
  string_array_calls_transform:
    required: false
    description: '<boolean> Enables the transformation of calls to the string array'
  string_array_calls_transform_threshold:
    required: false
    description: '<number> The probability that that calls to the string array will be transformed'
  string_array_encoding:
    required: false
    description: 'list> (comma separated, without whitespaces) Encodes each string in strings array using base64 or rc4 (this option can slow down your code speed). Values: none, base64, rc4. Default: none'
  string_array_indexes_type:
    required: false
    description: '<list> (comma separated, without whitespaces) Encodes each string in strings array using base64 or rc4 (this option can slow down your code speed). Values: hexadecimal-number, hexadecimal-numeric-string. Default: hexadecimal-number'
  string_array_index_shift:
    required: false
    description: '<boolean> Enables additional index shift for all string array calls'
  string_array_rotate:
    required: false
    description: '<boolean> Enable rotation of string array values during obfuscation'
  string_array_shuffle:
    required: false
    description: '<boolean> Randomly shuffles string array items'
  string_array_wrappers_count:
    required: false
    description: '<number> Sets the count of wrappers for the string array inside each root or function scope'
  string_array_wrappers_chained_calls: 
    required: false
    description: '<boolean> Enables the chained calls between string array wrappers'
  string_array_wrappers_parameters_max_count:
    required: false
    description: '<number> Allows to control the maximum number of string array wrappers parameters'
  string_array_wrappers_type:
    required: false
    description: '<string> Allows to select a type of the wrappers that are appending by the `--string-array-wrappers-count` option. Values: variable, function. Default: variable'
  string_array_threshold:
    required: false
    description: '<number> The probability that the literal string will be inserted into stringArray (Default: 0.8, Min: 0, Max: 1)'
  target:
    required: false
    description: '<string> Allows to set target environment for obfuscated code. Values: browser, browser-no-eval, node. Default: browser'
  transform_object_keys:
    required: false
    description: '<boolean> Enables transformation of object keys'
  unicode_escape_sequence:
    required: false
    description: '<boolean> Allows to enable/disable string conversion to unicode escape sequence'

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.input_path }}
    - ${{ inputs.output_path }}
    - ${{ inputs.control_flow_flattening }}
    - ${{ inputs.control_flow_flattening_threshold }}
    - ${{ inputs.dead_code_injection }}
    - ${{ inputs.dead_code_injection_threshold }}
    - ${{ inputs.debug_protection }}
    - ${{ inputs.debug_protection-interval }}
    - ${{ inputs.disable_console_output }}
    - ${{ inputs.domain_lock }}
    - ${{ inputs.domain_lock_redirect_url }}
    - ${{ inputs.exclude }}
    - ${{ inputs.force_transform_strings }}
    - ${{ inputs.identifier_names_cache_path }}
    - ${{ inputs.identifier_names_generator }}
    - ${{ inputs.identifiers_prefix }}
    - ${{ inputs.identifiers_dictionary }}
    - ${{ inputs.ignore_imports }}
    - ${{ inputs.log }}
    - ${{ inputs.numbers_to_expressions }}
    - ${{ inputs.options_preset }}
    - ${{ inputs.reserved_names }}
    - ${{ inputs.reserved_strings }}
    - ${{ inputs.rename_globals }}
    - ${{ inputs.rename_properties }}
    - ${{ inputs.rename_properties_mode }}
    - ${{ inputs.seed }}
    - ${{ inputs.self_defending }}
    - ${{ inputs.simplify }}
    - ${{ inputs.source_map }}
    - ${{ inputs.source_map_base_url }}
    - ${{ inputs.source_map_file_name }}
    - ${{ inputs.source_map_mode }}
    - ${{ inputs.source_map_sources_mode }}
    - ${{ inputs.split_strings }}
    - ${{ inputs.split_strings_chunk_length }}
    - ${{ inputs.string_array }}
    - ${{ inputs.string_array_calls_transform }}
    - ${{ inputs.string_array_calls_transform_threshold }}
    - ${{ inputs.string_array_encoding }}
    - ${{ inputs.string_array_indexes_type }}
    - ${{ inputs.string_array_index_shift }}
    - ${{ inputs.sring_array_rotate }}
    - ${{ inputs.string_array_shuffle }}
    - ${{ inputs.string_array_wrappers_count }}
    - ${{ inputs.string_array_wrappers_chained_calls }}
    - ${{ inputs.string_array_wrappers_parameters_max_count }}
    - ${{ inputs.string_array_wrappers_type }}
    - ${{ inputs.string_array_threshold }}
    - ${{ inputs.target }}
    - ${{ inputs.transform_object_keys }}
    - ${{ inputs.unicode_escape_sequence }}

branding:
  icon: 'package'
  color: 'green'