name: 'Github Action javascript-obfuscator'
author: Kevin Rohn
description: 'Obfuscate javascript by using the javascript-obfuscator'
inputs:
  input-path: 
    description: 'Single file or directory'
    required: true
  output-path: 
    description: 'Output path for single file or directory'
    required: true

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.input-path }}
    - ${{ inputs.output-path}}

branding:
  icon: 'package'
  color: 'green'