name: "Obfuscate js test application"
on: 
  push:

jobs:
  test-js-obfuscation:
    runs-on: ubuntu-latest

    steps:
      - name: Cleanup workspace path
        uses: mickem/clean-after-action@v1

      - name: Set current branch ref
        id: git_info
        run: |
          echo "::set-output name=branch::${GITHUB_REF##*/}"
          echo "::set-output name=hash::$(git rev-parse --short \"$GITHUB_SHA\")"

      - uses: actions/checkout@v3
        with:
          ref: ${{ steps.git_info.outputs.branch }}

      - uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: Execute without obfuscation
        run: |
          npm --prefix example install
          node example/index.js
      
      - name: Create distribution path
        run: |
         mkdir -p dist
         ls -lah

      - uses: ./action.yml
        with:
          input-path: example
          output-path: dist
        